### ISSUE TITLE
Error: .gobgpapi.GetRibRequest#family is not a field: undefined

### ISSUE THREAD

**Issue by DavidFlamini** [codeout/gobgp-node#1]
Hi, we are getting this when trying the "Show routes in gobgpd" example.

_Error: .gobgpapi.GetRibRequest#family is not a field: undefined_

Any leads would be appreciated.

Thanks.

**Comment by codeout** [comment]
Hi, which commit of gobgp are you using?

``` zsh
cd $GOPATH/src/github.com/osrg/gobgp && git log -1 --oneline
```

**Comment by DavidFlamini** [comment]
I'm using latest:

``` bash
# cd $GOPATH/src/github.com/osrg/gobgp && git log -1 --oneline
ed62f3f Add shorter prefix search
```

---

I got it working this way:

``` javascript
//(...)

var ipv4AFI = 0x01;
var mplsVpnSAFI = 0x80;

var familyVPNv4 = (ipv4AFI << 16) + mplsVpnSAFI;

gobgp.getRib({table:{family: familyVPNv4}}, function(err, table) {
  console.log(table);
});
```

but then I got this:

``` javascript
/workspace/devenv/tmp/node_modules/gobgp/index.js:25
          table.destinations.forEach(function(destination) {
                            ^

TypeError: Cannot read property 'forEach' of undefined
    at /workspace/devenv/tmp/node_modules/gobgp/index.js:25:29
```

turns out the 'destinations' array is now "one level down", so I fixed it like this:

``` javascript
// file: gobgp/index.js:25
--  table.destinations.forEach(function(destination) {
++ table.table.destinations.forEach(function(destination) {
```

and, for the sake of completeness, I changed my code to this:

``` javascript
//(...)

//(...)
gobgp.getRib({table:{family: familyVPNv4}}, function(err, result) {
  console.log(result.table);
});
```

Thanks!

**Comment by codeout** [comment]
Pushed gobgp-node 0.1.2 which supports the latest gobgp. (Not `npm publish` yet)
Could you try it with your original code?

``` zsh
npm install https://github.com/codeout/gobgp-node
```

If it works for you, I'll publish a newer npm package.

**Comment by DavidFlamini** [comment]
Hi, I get a reference error: "table is not defined"

/workspace/devenv/tmp/node_modules/gobgp/index.js:38
            return callback(null, table);
                                  ^

ReferenceError: table is not defined
    at Object.callback (/workspace/devenv/tmp/node_modules/gobgp/index.js:38:35)
    at /workspace/devenv/tmp/node_modules/gobgp/node_modules/grpc/src/node/src/client.js:422:14

**Comment by codeout** [comment]
Hi, thank you for your testing. The reference error should be fixed.
Could you try again please?

**Comment by DavidFlamini** [comment]
It worked like a charm! Thank you for fixing!

**Comment by codeout** [comment]
Published fixed version of npm package🎉 Thank you!
